import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "@/providers/convexClientProvider";
import { TunnelToolbar } from "@tunnel/nextjs";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>
          {children}
          {(process.env.NODE_ENV !== "development") && (
          <TunnelToolbar
            projectId={process.env.TUNNEL_PROJECT_ID as string}
          />
        )}
        </ConvexClientProvider>
      </body>
    </html>
  );
}
